### ISSUE TITLE
ADDing without CREATEing

### ISSUE THREAD

**Issue by abiank** [danni-m/redis-tsdb#8]
It looks like the previous version CREATEd a TS when you ADDed to a nonexistant key. Now it gives an error.  I'd like to revert back to the old behaviour, any tips on where to look?

**Comment by danni-m** [comment]
@abiank I'm sorry its not working for you.
in `module.c` the function `TSDB_add` checks if key exists, the older version created the key with the default values.

**Comment by abiank** [comment]
Thanks! I'll try and patch it.

**Comment by danni-m** [comment]
@abiank I removed  this feature because I felt that using a time series without a retention policy will probably lead to a OOM.
Would you provide some more info on how and why you use the module?
